### ISSUE TITLE
Synopsys Detect 7.x

### ISSUE THREAD

**Issue by jsimoni** [blackducksoftware/github-action#10]
I would like the GitHub Action to support Synopsys Detect 7.x
https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/642351242/Releases+Notes

**Comment by binoy-medhi-by** [comment]
+1 as it's breaking for Gradle 6.8 
https://github.com/blackducksoftware/synopsys-detect/issues/316

**Comment by gautambaghel** [comment]
fixed on the latest release, readme has more instructions on how to invoke
