### ISSUE TITLE
Gradle 7 and Blackduck GitHub action

### ISSUE THREAD

**Issue by ivan-caspeta-by** [blackducksoftware/github-action#14]
Hi everyone ... we are migrating to Gradle 7 in our projects and we are seeing an error with the blackduck GHA
 

* Where: 

587Initialization script '/home/runner/blackduck/runs/2021-09-10-04-05-27-395/shared/gradle/init-detect.gradle' line: 40 

588 

589* What went wrong: 

590Execution failed for task ':dependencies'. 

591> No signature of method: org.gradle.api.tasks.diagnostics.internal.dependencies.AsciiDependencyReportRenderer.startProject() is applicable for argument types: (org.gradle.api.internal.project.DefaultProject_Decorated) values: [root project 'jdp-common']
 
Has anyone seeing something similar? 
 
We tried using version 2.1 of the GHA, but that didn't work either

**Comment by kamimanzoor** [comment]
@ivan-caspeta-by  we encountered the same issue. It seems like Synopsys Detect version 6.x is causing this issue. We used version 7 as below to fix it:
``` yml
- name: Synopsys Detect
   uses: blackducksoftware/github-action@v2
   with:
     version: 7
```
Here is [ref](https://github.com/blackducksoftware/github-action#example-yaml-config-for-synopsys-detect-version-7) on how to specify version.
